name: Run on any Push event
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      #- uses: actions/checkout@master
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: '3.10.12'
          architecture: 'x64'
      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install -r requirements.txt
      - name: test
        run: cd src && pytest
      - name: Tests report
        run: coverage report
      - name: mypy
        run: mypy .
      - name: black
        run: black --diff --check .
      - name: isort
        run: isort --check-only .
      - name: flake8
        run: flake8 .
